# Generated by Django 4.1.4 on 2022-12-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='title',
            new_name='name',
        ),
    ]
