# Generated by Django 4.1.4 on 2022-12-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_thread_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='file',
        ),
    ]
