# Generated by Django 4.1.4 on 2022-12-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_thread_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.category', verbose_name='Category'),
        ),
    ]
