# Generated by Django 4.1.4 on 2022-12-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='file',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
